### ISSUE TITLE
navbar text not readable on dark backgrounds

### ISSUE THREAD

**Issue by kayleesk** [baller7215/uci-cansat-website#1]
e.g. home page
![image](https://github.com/user-attachments/assets/2978eea7-65c1-4cd8-b598-7fd028e9ac9a)

about page
![image](https://github.com/user-attachments/assets/639300ae-369b-49b3-9997-221ba26258a5)

projects page
![image](https://github.com/user-attachments/assets/78c21a0b-2989-4ff2-baab-d7c7e628bccb)

**Comment by baller7215** [comment]
<img width="1800" alt="Screenshot 2024-10-16 at 11 25 12 PM" src="https://github.com/user-attachments/assets/82ceb75f-bb1d-4dcb-920b-181dee5a4490">

hi kaylee, do you potentially have any extensions or anything that would change or manipulate the colors of the text? i was able to test it on my friend's windows laptop on microsoft edge, and the text doesn't seem to to have that problem. the text appeared to be light grey color, similar to the image i have attached here.
