### ISSUE TITLE
footer text misaligned

### ISSUE THREAD

**Issue by kayleesk** [baller7215/uci-cansat-website#3]
"UCI CanSat" and address are not aligned with the right-hand side text

![image](https://github.com/user-attachments/assets/025d24ac-a1a1-45c9-9948-726b83a23f58)

**Comment by baller7215** [comment]
fixed!
<img width="1800" alt="Screenshot 2024-10-17 at 12 27 04 AM" src="https://github.com/user-attachments/assets/df4c9393-cd3c-4bf6-a1f5-7c35bae16fac">
