### ISSUE TITLE
collapsing cards causes alignment to change while loading

### ISSUE THREAD

**Issue by kayleesk** [baller7215/uci-cansat-website#9]
cards start center-aligned, like this:

![image](https://github.com/user-attachments/assets/6b1b47e5-235e-4d7a-88c4-ae9823b8a1c9)

but when collapsed, moves to the left until loaded:
![image](https://github.com/user-attachments/assets/9dd14473-06aa-4850-b489-ab03fb269b06)

(moves back when loaded, though)

**Comment by kayleesk** [comment]
same issue on news archive cards, sponsor cards

**Comment by baller7215** [comment]
cards for team, projects, and sponsors should be fine now. going to come back to news archive cards soon!

**Comment by baller7215** [comment]
fixed news and updates cards
